### PR TITLE
Hotfix/combo deselect

### LINKED ISSUE #2: [bug] Full card combo select bug
In this game, the player is able to make card combo by clicking on them and grouping the ones with same type, but, the first card selected must respect the card on the top stack card (since the next play must respect the last one).

Being minded about that, we have the following problem:
- When selecting a full card combo and de-selecting de first combo card, the combo works even if the first card of the combo does not start with a valid type that matches the top stack card.

### PR DESCRIPTION
**Pull request by ArcaneDiver**
Hey 👋, here is my PR to resolve #2. 
Resolution: when i deselect a card i check that if the card on the top of the card stack is at the same color of the deselected card and if there is no other card with the same color or type then all cards are deselected.

### CODE REVIEW

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver! Thanks for making this pull request!

I'll make a code review on this weekend 😁

**Review by guilhermebkel — CHANGES_REQUESTED** [review]
## Code Review

Just gave I look at the code and, at first I thought you almost got the idea of the core game rules (even if I did not write that on the README, what I think that I have to do being honest), so this was really good 😊

Now, some refactors I find to be good to follow the project patterns and keep the code the same on all the base while following the business logic:

**1. Some semicolons/single quote:**

Since in this project it is a code standard to use **single quotes** and to not use **semicolons**, it would be better to make some changes on that parts 😁


**2. Statements without brackets:**

By following the same idea of code standard, since in the project it is normal to use brackets on statements, it would be better to use it on if/else statements. Ex: if {} else {}


**3. The new validation:**



Since we always need to verify if the first card of the combo is matching the top stack card, it would be better to validate the new first card of the combo instead all cards, because in the game we usually play like:

I select the cards in this sequence:
[1-RED, 2-BLUE, 3-RED]

And the top stack card is:
[4-RED]

If I remove the first card of the combo, the new selected cards would be:
[2-BLUE, 3-RED]

But, since the first card of the combo is a blue one, it does not match the red of the top stack card, so it is not a valid play.

## Final considerations

I thought that you did really great by doing that without knowing all the business rules and, noticed that you gave some refactor to use directly the selectedCards of store instead of getting it from the lastState, what I find to be better since that were nested methods to do this change and you helped using only one 😁

If you have some doubt about the review or disagree with something, please tell me. Thanks again for helping improving this game! 😉

**Comment by ArcaneDiver** [comment]
Hey, first I would like to congratulate you on the fantastic code review.
About the first two points, i'll make as soon as possible a commit that will refractor the code following you code standards. But i think that you should change some eslint settings in order to highlight practices that does not follow your code standards.

But about the third point i'm going to make another commit that modify a little bit the if statement that check if among the remaining cards there is a card that can still be part of the combo because a card can still be part of a meld if and only if the card is the same type as the top card. About checking only the first card I think you are right so I will change that too.

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver!

Thanks for replying!
I'll try to add these code standard rules to ESLint 😁

**Comment by ArcaneDiver** [comment]
If you would i could make another PR with eslint settings according to your code base rules.

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver!

I would be really grateful if you do that PR adding the new eslint rules 😊

I've noticed you added the code review changes to to other PRs, I'll give a look at it soon and merge it 😁

Thanks for helping!

**Review by guilhermebkel — APPROVED** [review]
Everything is great here as well 😁

**Pull request merged**
