### PR TITLE
Hotfix/mobile disconnect

### LINKED ISSUE #4: [bug] Socket disconnection on mobile
When players get into the **Table/Room Page** on mobile devices and minimizes the Browser, for some reason it causes a disconnection instantly on some devices.

So, being minded about that, we have two possible problems:
- When this disconnection happens, the disconnected player does not get a feedback about it.
- The disconnected player has to reload the page to connect to socket again, because there is no auto connection in case of disconnections.

### PR DESCRIPTION
**Pull request by ArcaneDiver**
Hey, finally here is my PR to resolve #4 🥳.
Please write me if something has to be changed 🤗.

### CODE REVIEW

**Comment by guilhermebkel** [comment]
Hello! I'll give a code review soon! 😁

**Comment by ArcaneDiver** [comment]
Ok i just read the code review of the other PR then as soon as possible i'll make a new commit that implements your code standards.

**Comment by guilhermebkel** [comment]
Got it! I'll review the standards that are not followed on this PR just to help you finding it when you make a refactor, but if you've already made just ignore that part of the code review ✌🏻

**Review by guilhermebkel — CHANGES_REQUESTED** [review]
## Code review

Hello! I gave a look at the code and everything about logic looks really fine! I thought that the idea of creating the function **getPlayerData** to reuse it later was great. Besides, I looked at the **Disconnect** component and noticed that you followed correctly the Material UI implementation and made the export following the project standards. You did really great! 😁

I just have some comments about code standards again:

**1. Variable name:**



Now that we're using two seconds on ping, the variable name could be **twoSecondsInMilliseconds** to improve readability.

**2. Code standards**






Some code standards that need to be followed on the project (like semicolon, etc). If you have already made this changes just ignore that part.

**Review by guilhermebkel — APPROVED** [review]
Everything is great 😁

**Pull request merged**
