### PR TITLE
Hotfix/eslint config

### PR DESCRIPTION
**Pull request by ArcaneDiver**
Hey 👋, i finally completed to set eslint config.
I noticed that in `unoenty` package eslint was set only to use `react-app` rules then i extended even the root config and that generated a lots of errors and warnings.
I added two new commands:
- lint: runs `eslint` and shows every error and warning
- lint:fix: runs `eslint` and try to fix errors (some errors/warning cannot be fixed)

Please feel free to write me for any clarification🤗.

### CODE REVIEW

**Comment by guilhermebkel** [comment]
Hello @ArcaneDiver! Thanks for creating the new rules. You said that erros/warnings appeared and maybe that's a good thing 😆 (because some time ago I started feeling like eslint was not working well on the packages haha).

I'll give a look on your commit soon! 😃

**Review by guilhermebkel — CHANGES_REQUESTED** [review]
Hello @ArcaneDiver! Just gave a look at the changes and I think you added the new rules correctly and the errors/warnings started appearing for good, since it was not happening before. So, if error/warning appears, it means that the eslint is now working correctly.

There's one thing a noticed on the build that was a typing error that now is being caught, so it is needed to solve that in order to make the final build to work:
DeepinScreenshot_20201010172600

In the end, I recommend you to run a **npm run build** locally in order to check if new build errors occurs due to typing or eslint validations.

Thanks for being proactive to solve this app issues 😁

**Comment by ArcaneDiver** [comment]
Hey 👋,
I don't know why but i hadn't fixed some types.
Anyways i fixed them and i also added some scripts in order to check types before commit.

**Review by guilhermebkel — APPROVED** [review]
Hello @ArcaneDiver! I just gave a look on the modifications and everything looks to be working well!

Thanks for adding new commands to validate code on commit hook and as well for fixing the typing issues that suddenly appeared after configuring ESLint the right way! 😁

**Pull request merged**
